title: flatMap(Oslo) 2017
email: flatmap@arktekk.no
description: > # flatMap(Oslo) 2017 functional programming conference
baseurl: ""
url: "http://2017.flatmap.no"

destination: docs
include: ["_pages"]
permalink: /:title/
exclude: [vendor]

includes:
  - _pages

markdown: kramdown

gems:
- susy
